// SPDX-License-Identifier: Apache-2.0

using System.Reflection;
using Google.Protobuf.Reflection;

namespace Substrait.MetadataGenerator;

internal static class FacadeGenerator
{
    internal static IReadOnlyDictionary<string, string> Generate(IEnumerable<MessageDescriptor> roots)
    {
        var messages = new Dictionary<string, MessageDescriptor>(StringComparer.Ordinal);
        var pending = new Stack<MessageDescriptor>(roots);
        while (pending.TryPop(out MessageDescriptor? message))
        {
            if (!messages.TryAdd(message.FullName, message))
            {
                continue;
            }

            foreach (FieldDescriptor field in message.Fields.InFieldNumberOrder())
            {
                if (field.IsMap || field.FieldType == FieldType.Group)
                {
                    throw new NotSupportedException($"Metadata field {field.FullName} has an unsupported shape: {field.FieldType}, map={field.IsMap}.");
                }

                if (field.FieldType == FieldType.Message)
                {
                    pending.Push(field.MessageType);
                }
            }
        }

        var files = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (MessageDescriptor message in messages.Values.OrderBy(message => message.FullName, StringComparer.Ordinal))
        {
            string name = FacadeName(message) + ".g.cs";
            if (!files.TryAdd(name, GenerateMessage(message)))
            {
                throw new InvalidOperationException($"Metadata facade name collision for {message.FullName}: {name}.");
            }
        }

        return files;
    }

    private static string GenerateMessage(MessageDescriptor message)
    {
        string name = FacadeName(message);
        string proto = TypeName(message.ClrType);
        var fields = message.Fields.InFieldNumberOrder();
        List<string> lines =
        [
            "// <auto-generated/>",
            "// SPDX-License-Identifier: Apache-2.0",
            "// Generated by Substrait.MetadataGenerator. Do not edit.",
            "#nullable enable",
            "",
            "namespace Substrait.Core.Metadata;",
            "",
            "/// <summary>",
            $"/// An immutable, read-only facade for <see cref=\"{proto}\"/>.",
            "/// </summary>",
            "/// <remarks>",
            "/// Public imports and exports are deep copies. Equality uses protobuf structural equality.",
            "/// </remarks>",
            $"public sealed class {name} : global::System.IEquatable<{name}>",
            "{",
            $"    private readonly {proto} value;",
            "",
            $"    private {name}({proto} value)",
            "    {",
            "        this.value = value;",
        ];

        foreach (FieldDescriptor field in fields)
        {
            string property = field.PropertyName;
            if (field.IsRepeated)
            {
                string elementType = ElementType(field);
                string initializer = field.FieldType == FieldType.Message
                    ? $"global::System.Array.AsReadOnly(value.{property}.Select({elementType}.FromOwnedProto).ToArray())"
                    : $"new global::System.Collections.ObjectModel.ReadOnlyCollection<{elementType}>(value.{property})";
                lines.Add($"        this.{property} = {initializer};");
            }
            else if (field.FieldType == FieldType.Message)
            {
                lines.Add($"        this.{property} = value.{property} is null ? null : {ElementType(field)}.FromOwnedProto(value.{property});");
            }
        }

        lines.Add("    }");
        foreach (FieldDescriptor field in fields)
        {
            string property = field.PropertyName;
            string elementType = ElementType(field);
            lines.Add("");
            lines.Add($"    /// <summary>Gets the read-only value of <see cref=\"{proto}.{property}\"/>.</summary>");
            if (field.IsRepeated)
            {
                lines.Add($"    public global::System.Collections.Generic.IReadOnlyList<{elementType}> {property} {{ get; }}");
            }
            else if (field.FieldType == FieldType.Message)
            {
                lines.Add($"    public {elementType}? {property} {{ get; }}");
            }
            else if (field.HasPresence)
            {
                string condition;
                if (field.RealContainingOneof is OneofDescriptor oneof)
                {
                    PropertyInfo discriminator = CaseProperty(oneof);
                    condition = $"(int)this.value.{discriminator.Name} == {field.FieldNumber}";
                }
                else
                {
                    string presence = "Has" + property;
                    if (message.ClrType.GetProperty(presence)?.PropertyType != typeof(bool))
                    {
                        throw new InvalidOperationException($"Cannot resolve presence property for {field.FullName}.");
                    }

                    condition = $"this.value.{presence}";
                }

                lines.Add($"    public {elementType}? {property} => {condition} ? this.value.{property} : null;");
            }
            else
            {
                lines.Add($"    public {elementType} {property} => this.value.{property};");
            }
        }

        foreach (OneofDescriptor oneof in message.Oneofs.Where(oneof => !oneof.IsSynthetic))
        {
            PropertyInfo property = CaseProperty(oneof);
            lines.Add("");
            lines.Add($"    /// <summary>Gets the selected case of <see cref=\"{proto}.{property.Name}\"/>.</summary>");
            lines.Add($"    public {TypeName(property.PropertyType)} {property.Name} => this.value.{property.Name};");
        }

        lines.AddRange(
        [
            "",
            "    /// <summary>Creates an immutable snapshot without taking ownership of the caller's message.</summary>",
            "    /// <param name=\"value\">The message to copy. Do not mutate it concurrently with this call.</param>",
            "    /// <returns>A facade over a deep copy of the message.</returns>",
            $"    public static {name} FromProto({proto} value)",
            "    {",
            "        if (value is null)",
            "        {",
            "            throw new global::System.ArgumentNullException(nameof(value));",
            "        }",
            "",
            "        return FromOwnedProto(value.Clone());",
            "    }",
            "",
            "    /// <summary>Returns a detached, mutable deep copy, including unknown fields.</summary>",
            "    /// <returns>A protobuf message which can be modified without affecting this facade.</returns>",
            $"    public {proto} ToProto() => this.value.Clone();",
            "",
            "    /// <inheritdoc/>",
            $"    public bool Equals({name}? other) => other is not null && this.value.Equals(other.value);",
            "",
            "    /// <inheritdoc/>",
            $"    public override bool Equals(object? obj) => obj is {name} other && this.Equals(other);",
            "",
            "    /// <inheritdoc/>",
            "    public override int GetHashCode() => this.value.GetHashCode();",
            "",
            "    /// <summary>",
            "    /// Wraps library-owned storage without cloning. Neither the message nor any mutable",
            "    /// descendant may subsequently be mutated or exposed outside the ownership boundary.",
            "    /// </summary>",
            $"    internal static {name} FromOwnedProto({proto} value)",
            "    {",
            "        if (value is null)",
            "        {",
            "            throw new global::System.ArgumentNullException(nameof(value));",
            "        }",
            "",
            $"        return new {name}(value);",
            "    }",
            "}",
            "",
        ]);
        return string.Join('\n', lines);
    }

    private static string ElementType(FieldDescriptor field) => field.FieldType switch
    {
        FieldType.Double => "double",
        FieldType.Float => "float",
        FieldType.Int64 or FieldType.SInt64 or FieldType.SFixed64 => "long",
        FieldType.UInt64 or FieldType.Fixed64 => "ulong",
        FieldType.Int32 or FieldType.SInt32 or FieldType.SFixed32 => "int",
        FieldType.UInt32 or FieldType.Fixed32 => "uint",
        FieldType.Bool => "bool",
        FieldType.String => "string",
        FieldType.Bytes => "global::Google.Protobuf.ByteString",
        FieldType.Enum => TypeName(field.EnumType.ClrType),
        FieldType.Message => FacadeName(field.MessageType),
        _ => throw new NotSupportedException($"Metadata field {field.FullName} has unsupported type {field.FieldType}."),
    };

    private static PropertyInfo CaseProperty(OneofDescriptor oneof)
    {
        string name = string.Concat(oneof.Name.Split('_').Select(part => char.ToUpperInvariant(part[0]) + part[1..])) + "Case";
        PropertyInfo? property = oneof.ContainingType.ClrType.GetProperty(name);
        if (property is null || !property.PropertyType.IsEnum
            || oneof.Fields.Any(field => !Enum.IsDefined(property.PropertyType, field.FieldNumber)))
        {
            throw new InvalidOperationException($"Cannot resolve the CLR case discriminator for {oneof.FullName}.");
        }

        return property;
    }

    private static string FacadeName(MessageDescriptor message)
    {
        var names = new Stack<string>();
        for (MessageDescriptor? current = message; current is not null; current = current.ContainingType)
        {
            names.Push(current.Name);
        }

        return "ReadOnly" + string.Concat(names);
    }

    private static string TypeName(Type type) =>
        "global::" + (type.FullName ?? throw new InvalidOperationException($"Missing CLR name for {type}.")).Replace('+', '.');
}
