<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageVersion Include="Antlr4BuildTasks" Version="12.14.0" />
    <PackageVersion Include="Google.Protobuf" Version="3.26.1" />
    <PackageVersion Include="Grpc.Tools" Version="2.62.0" />
    <PackageVersion Include="IndexRange" Version="1.0.3" />
    <PackageVersion Include="IsExternalInit" Version="1.0.3" />
    <PackageVersion Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="3.3.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.7.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.7.3" />
    <PackageVersion Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageVersion Include="System.Memory" Version="4.5.5" />
    <PackageVersion Include="YamlDotNet" Version="15.1.2" />
  </ItemGroup>
</Project>