<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageVersion Include="Google.Protobuf" Version="3.36.2" />
    <PackageVersion Include="IndexRange" Version="1.1.1" />
    <PackageVersion Include="IsExternalInit" Version="1.0.3" />
    <PackageVersion Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.4.1" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.4.1" />
    <PackageVersion Include="Substrait.Net.Antlr" Version="0.104.0" />
    <PackageVersion Include="Substrait.Net.Extensions" Version="0.104.0" />
    <PackageVersion Include="Substrait.Net.Protobuf" Version="0.104.0" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.12" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>