<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Substrait.Net</AssemblyName>
    <RootNamespace>Substrait</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>Substrait.Net</PackageId>
    <VersionPrefix>0.1.0</VersionPrefix>
    <Description>A library for creating, modifying, serializing, and processing Substrait plans in .NET.</Description>
    <PackageTags>Substrait;protobuf;query-plan</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1574;CA1305;CA1309;CA1310;CA1707;CA1708;CA1711;CA1712;CA1716;CA1720;CA1725;CA1805;CA1822;CA1852;CA1859;RS0026;RS0027</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" />
    <PackageReference Include="Antlr4BuildTasks" PrivateAssets="All" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="IndexRange" />
    <PackageReference Include="IsExternalInit" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Bcl.HashCode" />
    <PackageReference Include="System.Collections.Immutable" />
    <PackageReference Include="System.Memory" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="$(RepositoryRoot)third_party\substrait\proto\substrait\**\*.proto"
              ProtoRoot="$(RepositoryRoot)third_party\substrait\proto"
              GrpcServices="None" />

    <Antlr4 Include="$(RepositoryRoot)third_party\substrait\grammar\SubstraitType.g4">
      <Listener>false</Listener>
      <Visitor>true</Visitor>
      <GAtn>false</GAtn>
      <Package>Substrait.Antlr.Type</Package>
      <Error>true</Error>
    </Antlr4>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="$(RepositoryRoot)third_party\substrait\extensions\functions_aggregate_approx.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_aggregate_generic.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_arithmetic.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_boolean.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_comparison.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_datetime.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_logarithmic.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_rounding.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\functions_string.yaml;
                               $(RepositoryRoot)third_party\substrait\extensions\type_variations.yaml">
      <LogicalName>DefaultExtensions/%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(RepositoryRoot)README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>