// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: substrait/plan.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Substrait.Protobuf {

  /// <summary>Holder for reflection information generated from substrait/plan.proto</summary>
  public static partial class PlanReflection {

    #region Descriptor
    /// <summary>File descriptor for substrait/plan.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlanReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRzdWJzdHJhaXQvcGxhbi5wcm90bxIJc3Vic3RyYWl0GhdzdWJzdHJhaXQv",
            "YWxnZWJyYS5wcm90bxolc3Vic3RyYWl0L2V4dGVuc2lvbnMvZXh0ZW5zaW9u",
            "cy5wcm90byJYCgdQbGFuUmVsEh0KA3JlbBgBIAEoCzIOLnN1YnN0cmFpdC5S",
            "ZWxIABIiCgRyb290GAIgASgLMhIuc3Vic3RyYWl0LlJlbFJvb3RIAEIKCghy",
            "ZWxfdHlwZSKXAgoEUGxhbhJACg5leHRlbnNpb25fdXJpcxgBIAMoCzIoLnN1",
            "YnN0cmFpdC5leHRlbnNpb25zLlNpbXBsZUV4dGVuc2lvblVSSRJECgpleHRl",
            "bnNpb25zGAIgAygLMjAuc3Vic3RyYWl0LmV4dGVuc2lvbnMuU2ltcGxlRXh0",
            "ZW5zaW9uRGVjbGFyYXRpb24SJQoJcmVsYXRpb25zGAMgAygLMhIuc3Vic3Ry",
            "YWl0LlBsYW5SZWwSRAoTYWR2YW5jZWRfZXh0ZW5zaW9ucxgEIAEoCzInLnN1",
            "YnN0cmFpdC5leHRlbnNpb25zLkFkdmFuY2VkRXh0ZW5zaW9uEhoKEmV4cGVj",
            "dGVkX3R5cGVfdXJscxgFIAMoCUJXChJpby5zdWJzdHJhaXQucHJvdG9QAVoq",
            "Z2l0aHViLmNvbS9zdWJzdHJhaXQtaW8vc3Vic3RyYWl0LWdvL3Byb3RvqgIS",
            "U3Vic3RyYWl0LlByb3RvYnVmYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Substrait.Protobuf.AlgebraReflection.Descriptor, global::Substrait.Protobuf.ExtensionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Substrait.Protobuf.PlanRel), global::Substrait.Protobuf.PlanRel.Parser, new[]{ "Rel", "Root" }, new[]{ "RelType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Substrait.Protobuf.Plan), global::Substrait.Protobuf.Plan.Parser, new[]{ "ExtensionUris", "Extensions", "Relations", "AdvancedExtensions", "ExpectedTypeUrls" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Either a relation or root relation
  /// </summary>
  public sealed partial class PlanRel : pb::IMessage<PlanRel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlanRel> _parser = new pb::MessageParser<PlanRel>(() => new PlanRel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlanRel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Substrait.Protobuf.PlanReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanRel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanRel(PlanRel other) : this() {
      switch (other.RelTypeCase) {
        case RelTypeOneofCase.Rel:
          Rel = other.Rel.Clone();
          break;
        case RelTypeOneofCase.Root:
          Root = other.Root.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlanRel Clone() {
      return new PlanRel(this);
    }

    /// <summary>Field number for the "rel" field.</summary>
    public const int RelFieldNumber = 1;
    /// <summary>
    /// Any relation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Substrait.Protobuf.Rel Rel {
      get { return relTypeCase_ == RelTypeOneofCase.Rel ? (global::Substrait.Protobuf.Rel) relType_ : null; }
      set {
        relType_ = value;
        relTypeCase_ = value == null ? RelTypeOneofCase.None : RelTypeOneofCase.Rel;
      }
    }

    /// <summary>Field number for the "root" field.</summary>
    public const int RootFieldNumber = 2;
    /// <summary>
    /// The root of a relation tree
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Substrait.Protobuf.RelRoot Root {
      get { return relTypeCase_ == RelTypeOneofCase.Root ? (global::Substrait.Protobuf.RelRoot) relType_ : null; }
      set {
        relType_ = value;
        relTypeCase_ = value == null ? RelTypeOneofCase.None : RelTypeOneofCase.Root;
      }
    }

    private object relType_;
    /// <summary>Enum of possible cases for the "rel_type" oneof.</summary>
    public enum RelTypeOneofCase {
      None = 0,
      Rel = 1,
      Root = 2,
    }
    private RelTypeOneofCase relTypeCase_ = RelTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RelTypeOneofCase RelTypeCase {
      get { return relTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRelType() {
      relTypeCase_ = RelTypeOneofCase.None;
      relType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlanRel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlanRel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Rel, other.Rel)) return false;
      if (!object.Equals(Root, other.Root)) return false;
      if (RelTypeCase != other.RelTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (relTypeCase_ == RelTypeOneofCase.Rel) hash ^= Rel.GetHashCode();
      if (relTypeCase_ == RelTypeOneofCase.Root) hash ^= Root.GetHashCode();
      hash ^= (int) relTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (relTypeCase_ == RelTypeOneofCase.Rel) {
        output.WriteRawTag(10);
        output.WriteMessage(Rel);
      }
      if (relTypeCase_ == RelTypeOneofCase.Root) {
        output.WriteRawTag(18);
        output.WriteMessage(Root);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (relTypeCase_ == RelTypeOneofCase.Rel) {
        output.WriteRawTag(10);
        output.WriteMessage(Rel);
      }
      if (relTypeCase_ == RelTypeOneofCase.Root) {
        output.WriteRawTag(18);
        output.WriteMessage(Root);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (relTypeCase_ == RelTypeOneofCase.Rel) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rel);
      }
      if (relTypeCase_ == RelTypeOneofCase.Root) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Root);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlanRel other) {
      if (other == null) {
        return;
      }
      switch (other.RelTypeCase) {
        case RelTypeOneofCase.Rel:
          if (Rel == null) {
            Rel = new global::Substrait.Protobuf.Rel();
          }
          Rel.MergeFrom(other.Rel);
          break;
        case RelTypeOneofCase.Root:
          if (Root == null) {
            Root = new global::Substrait.Protobuf.RelRoot();
          }
          Root.MergeFrom(other.Root);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Substrait.Protobuf.Rel subBuilder = new global::Substrait.Protobuf.Rel();
            if (relTypeCase_ == RelTypeOneofCase.Rel) {
              subBuilder.MergeFrom(Rel);
            }
            input.ReadMessage(subBuilder);
            Rel = subBuilder;
            break;
          }
          case 18: {
            global::Substrait.Protobuf.RelRoot subBuilder = new global::Substrait.Protobuf.RelRoot();
            if (relTypeCase_ == RelTypeOneofCase.Root) {
              subBuilder.MergeFrom(Root);
            }
            input.ReadMessage(subBuilder);
            Root = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Substrait.Protobuf.Rel subBuilder = new global::Substrait.Protobuf.Rel();
            if (relTypeCase_ == RelTypeOneofCase.Rel) {
              subBuilder.MergeFrom(Rel);
            }
            input.ReadMessage(subBuilder);
            Rel = subBuilder;
            break;
          }
          case 18: {
            global::Substrait.Protobuf.RelRoot subBuilder = new global::Substrait.Protobuf.RelRoot();
            if (relTypeCase_ == RelTypeOneofCase.Root) {
              subBuilder.MergeFrom(Root);
            }
            input.ReadMessage(subBuilder);
            Root = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Describe a set of operations to complete.
  /// For compactness sake, identifiers are normalized at the plan level.
  /// </summary>
  public sealed partial class Plan : pb::IMessage<Plan>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Plan> _parser = new pb::MessageParser<Plan>(() => new Plan());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Plan> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Substrait.Protobuf.PlanReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Plan() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Plan(Plan other) : this() {
      extensionUris_ = other.extensionUris_.Clone();
      extensions_ = other.extensions_.Clone();
      relations_ = other.relations_.Clone();
      advancedExtensions_ = other.advancedExtensions_ != null ? other.advancedExtensions_.Clone() : null;
      expectedTypeUrls_ = other.expectedTypeUrls_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Plan Clone() {
      return new Plan(this);
    }

    /// <summary>Field number for the "extension_uris" field.</summary>
    public const int ExtensionUrisFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Substrait.Protobuf.SimpleExtensionURI> _repeated_extensionUris_codec
        = pb::FieldCodec.ForMessage(10, global::Substrait.Protobuf.SimpleExtensionURI.Parser);
    private readonly pbc::RepeatedField<global::Substrait.Protobuf.SimpleExtensionURI> extensionUris_ = new pbc::RepeatedField<global::Substrait.Protobuf.SimpleExtensionURI>();
    /// <summary>
    /// a list of yaml specifications this plan may depend on
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Substrait.Protobuf.SimpleExtensionURI> ExtensionUris {
      get { return extensionUris_; }
    }

    /// <summary>Field number for the "extensions" field.</summary>
    public const int ExtensionsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Substrait.Protobuf.SimpleExtensionDeclaration> _repeated_extensions_codec
        = pb::FieldCodec.ForMessage(18, global::Substrait.Protobuf.SimpleExtensionDeclaration.Parser);
    private readonly pbc::RepeatedField<global::Substrait.Protobuf.SimpleExtensionDeclaration> extensions_ = new pbc::RepeatedField<global::Substrait.Protobuf.SimpleExtensionDeclaration>();
    /// <summary>
    /// a list of extensions this plan may depend on
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Substrait.Protobuf.SimpleExtensionDeclaration> Extensions {
      get { return extensions_; }
    }

    /// <summary>Field number for the "relations" field.</summary>
    public const int RelationsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Substrait.Protobuf.PlanRel> _repeated_relations_codec
        = pb::FieldCodec.ForMessage(26, global::Substrait.Protobuf.PlanRel.Parser);
    private readonly pbc::RepeatedField<global::Substrait.Protobuf.PlanRel> relations_ = new pbc::RepeatedField<global::Substrait.Protobuf.PlanRel>();
    /// <summary>
    /// one or more relation trees that are associated with this plan.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Substrait.Protobuf.PlanRel> Relations {
      get { return relations_; }
    }

    /// <summary>Field number for the "advanced_extensions" field.</summary>
    public const int AdvancedExtensionsFieldNumber = 4;
    private global::Substrait.Protobuf.AdvancedExtension advancedExtensions_;
    /// <summary>
    /// additional extensions associated with this plan.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Substrait.Protobuf.AdvancedExtension AdvancedExtensions {
      get { return advancedExtensions_; }
      set {
        advancedExtensions_ = value;
      }
    }

    /// <summary>Field number for the "expected_type_urls" field.</summary>
    public const int ExpectedTypeUrlsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_expectedTypeUrls_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> expectedTypeUrls_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// A list of com.google.Any entities that this plan may use. Can be used to
    /// warn if some embedded message types are unknown. Note that this list may
    /// include message types that are ignorable (optimizations) or that are
    /// unused. In many cases, a consumer may be able to work with a plan even if
    /// one or more message types defined here are unknown.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> ExpectedTypeUrls {
      get { return expectedTypeUrls_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Plan);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Plan other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!extensionUris_.Equals(other.extensionUris_)) return false;
      if(!extensions_.Equals(other.extensions_)) return false;
      if(!relations_.Equals(other.relations_)) return false;
      if (!object.Equals(AdvancedExtensions, other.AdvancedExtensions)) return false;
      if(!expectedTypeUrls_.Equals(other.expectedTypeUrls_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= extensionUris_.GetHashCode();
      hash ^= extensions_.GetHashCode();
      hash ^= relations_.GetHashCode();
      if (advancedExtensions_ != null) hash ^= AdvancedExtensions.GetHashCode();
      hash ^= expectedTypeUrls_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      extensionUris_.WriteTo(output, _repeated_extensionUris_codec);
      extensions_.WriteTo(output, _repeated_extensions_codec);
      relations_.WriteTo(output, _repeated_relations_codec);
      if (advancedExtensions_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AdvancedExtensions);
      }
      expectedTypeUrls_.WriteTo(output, _repeated_expectedTypeUrls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      extensionUris_.WriteTo(ref output, _repeated_extensionUris_codec);
      extensions_.WriteTo(ref output, _repeated_extensions_codec);
      relations_.WriteTo(ref output, _repeated_relations_codec);
      if (advancedExtensions_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(AdvancedExtensions);
      }
      expectedTypeUrls_.WriteTo(ref output, _repeated_expectedTypeUrls_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += extensionUris_.CalculateSize(_repeated_extensionUris_codec);
      size += extensions_.CalculateSize(_repeated_extensions_codec);
      size += relations_.CalculateSize(_repeated_relations_codec);
      if (advancedExtensions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AdvancedExtensions);
      }
      size += expectedTypeUrls_.CalculateSize(_repeated_expectedTypeUrls_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Plan other) {
      if (other == null) {
        return;
      }
      extensionUris_.Add(other.extensionUris_);
      extensions_.Add(other.extensions_);
      relations_.Add(other.relations_);
      if (other.advancedExtensions_ != null) {
        if (advancedExtensions_ == null) {
          AdvancedExtensions = new global::Substrait.Protobuf.AdvancedExtension();
        }
        AdvancedExtensions.MergeFrom(other.AdvancedExtensions);
      }
      expectedTypeUrls_.Add(other.expectedTypeUrls_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            extensionUris_.AddEntriesFrom(input, _repeated_extensionUris_codec);
            break;
          }
          case 18: {
            extensions_.AddEntriesFrom(input, _repeated_extensions_codec);
            break;
          }
          case 26: {
            relations_.AddEntriesFrom(input, _repeated_relations_codec);
            break;
          }
          case 34: {
            if (advancedExtensions_ == null) {
              AdvancedExtensions = new global::Substrait.Protobuf.AdvancedExtension();
            }
            input.ReadMessage(AdvancedExtensions);
            break;
          }
          case 42: {
            expectedTypeUrls_.AddEntriesFrom(input, _repeated_expectedTypeUrls_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            extensionUris_.AddEntriesFrom(ref input, _repeated_extensionUris_codec);
            break;
          }
          case 18: {
            extensions_.AddEntriesFrom(ref input, _repeated_extensions_codec);
            break;
          }
          case 26: {
            relations_.AddEntriesFrom(ref input, _repeated_relations_codec);
            break;
          }
          case 34: {
            if (advancedExtensions_ == null) {
              AdvancedExtensions = new global::Substrait.Protobuf.AdvancedExtension();
            }
            input.ReadMessage(AdvancedExtensions);
            break;
          }
          case 42: {
            expectedTypeUrls_.AddEntriesFrom(ref input, _repeated_expectedTypeUrls_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
