<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <SmokeTestTargetFramework Condition="'$(SmokeTestTargetFramework)' == ''">net8.0</SmokeTestTargetFramework>
    <TargetFramework>$(SmokeTestTargetFramework)</TargetFramework>
    <SmokeTestPackageVersion Condition="'$(SmokeTestPackageVersion)' == ''">0.1.0-preview.1</SmokeTestPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Substrait.Net" VersionOverride="$(SmokeTestPackageVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="System.Memory" />
  </ItemGroup>
</Project>